version: 2
registries:
  maven-nexus3:
    type: maven-repository
    url: https://nexus3.trifork.com/repository/ehealth-maven-releases/
    username: ${{secrets.FUT_NEXUS_USERNAME}}
    password: ${{secrets.FUT_NEXUS_PASSWORD}}
updates:
  - package-ecosystem: maven
    directory: "/"
    registries:
      - maven-nexus3
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 10
    ignore:
    - dependency-name: org.owasp:dependency-check-maven
      versions:
      - 6.1.0
      - 6.1.2
      - 6.1.3
      - 6.1.4
